is_val: false
pairs: 1 #3
min_dist: 0.2
episodes_per_pair: 1 #2000
steps_per_episode: 100
image_size: [64, 64]
model_path: mujoco_menagerie/franka_emika_panda/scene.xml
camera_name: top_view #top_view, default
save_dir: pldm_envs/franka/presaved_datasets
specify_init_position: true #初期姿勢を指定するか

confirm_ik_result: true
confirm_dist: true
make_video: true
confirm_ee_trajectory: true
confirm_data: true

start_goal_x_range: [0.365, 0.665]
start_goal_y_range: [-0.15, 0.15]
start_goal_z_range: [0.05, 0.05]

x_range: [0.315, 0.715] 
y_range: [-0.2, 0.2] 
z_range: [0.1, 0.1] 

#sample_method
#direction --> 方向ベクトルをサンプリング
#uniform --> 一様分布
#uniform_constrain --> 一様分布だが, 現在の位置との距離がmax_dist 未満になるまで繰り返す

sample_method: 'direction' #'direction' or 'uniform' or 'uniform_constrain'
margin_ratio: 0.80
sample_direction:
  dist_range: [0.0, 0.01]
  max_loop: 100
  freeze_z: true
  prob_dist: 'vonmises' # uniform, vonmises
  vonmises:
    kappa: 20.0
sample_uniform_constrain: #距離制限つき一様分布
  max_dist: 0.01
  max_loop: 100


freeze_quat: false
ee_x: [1, 0, 0]
ee_y: [0, -1, 0]
ee_z: [0, 0, -1]
target_sampling_step: 1 #target_xyzをサンプリングするデータセットタイムステップ間隔
steps: 200 #200 #一度のmove_franka_to_xyzで進むmujoco上のステップ数
tol: 1e-2
rot_weight: 0.1 #IKの回転ずれ許容量の重み
alpha: 0.8

visualize_target_trajectory: true
count_contact: true