n_steps: &n_steps 3
val_n_steps: *n_steps
env_name: &env_name franka

base_lr: 0.041037
data:
  dataset_type: DatasetType.Franka
  normalize: true
  normalize_mode: "zscore"
  normalize_actions_mode: "zscore"
  min_states_val: 0.0
  max_states_val: 1.0
  min_actions_val: -1.0
  max_actions_val: 1.0
  min_locations_val: 0.0
  max_locations_val: 1.0
  min_propio_pos_val: 0.0
  max_propio_pos_val: 1.0
  min_propio_vel_val: 0.0
  max_propio_vel_val: 1.0
  min_bluebox_locs_val: 0.0
  max_bluebox_locs_val: 1.0
  franka_config:
    env_name: *env_name
    random_actions: false
    img_size: 64
    alpha: 0.6
    batch_size: 16 #128
    beta: 0.4
    crop_length: null
    images_path: pldm_envs/franka/presaved_datasets/pairs_1_ep_1_timestep_10_sample_mix_direction_towards_bluebox_1p00_1p00_view_top_reverse/images.npy
    path: pldm_envs/franka/presaved_datasets/pairs_1_ep_1_timestep_10_sample_mix_direction_towards_bluebox_1p00_1p00_view_top_reverse/data.p
    location_only: false
    # normalize: true
    num_workers: 0 #10
    prioritized: false
    quick_debug: false
    sample_length: *n_steps
    seed: 0
    stack_states: 1
    train: true
    val_fraction: 0.2
    
epochs: 5 #10
eval_at_beginning: false
eval_during_training: false
eval_every_n_epochs: 2
eval_mpcs: 20
eval_only: false
hjepa:
  l1_n_steps: *n_steps
  train_l1: true
  freeze_l1: false
  disable_l2: true
  level1:
    backbone:
      arch: vjepa2 #menet6/vjepa2
      backbone_subclass: d4rl_a
      backbone_mlp: null
      backbone_width_factor: 2
      input_dim: 14
      channels: 3
      propio_dim: 14
      propio_encoder_arch: 'id'

      vjepa2_repo: "facebook/vjepa2-vitl-fpc64-256"
      vjepa2_freeze: true
      vjepa2_use_single_frame: true #現在未使用
      vjepa2_output: "spatial"   # "spatial" or "cls" #現在未使用
      vjepa2_adapter_channels: 16
      vjepa2_adapter_hw: 26
      vjepa2_chunk_size: 16
    predictor:
      residual: true
      action_encoder_arch: 'id'
      predictor_arch: conv2
      predictor_subclass: franka_b_p
      rnn_converter_arch: ''
      rnn_layers: 1
      rnn_state_dim: 512
      z_dim: 0
      z_min_std: 0.1
    encode_only: false
    use_z_goal: false
    action_dim: 7
    momentum: 0.99
  step_skip: 4
load_checkpoint_path: null #pldm/checkpoints/franka_20250828_203109/epoch=10_sample_step=3410000.ckpt
load_l1_only: false

alpha: 0.0 #0.0 #current_state = (1 - alpha) * next_state + alpha * teacher_state
use_opn_loss_func: &use_opn_loss_func false #現在はopen_objectives を共通の損失関数として使用
objectives_l1:
  idm:
    action_dim: 7
    coeff: 5.3964 #5.3964
    arch: 'conv'
    use_pred: false
    arch_subclass: a
  clsd_objectives: #実際はclosed
  - ObjectiveType.VICRegObs
  # - ObjectiveType.VICReg
  # - ObjectiveType.SIGReg
  # - ObjectiveType.IDM
  - ObjectiveType.PredictionPropio
  opn_objectives:
  - ObjectiveType.VICRegObs
  # - ObjectiveType.VICReg
  # - ObjectiveType.SIGReg
  # - ObjectiveType.IDM
  - ObjectiveType.PredictionPropio
  vicreg_obs:
    adjust_cov: true
    cov_chunk_size: null
    cov_coeff: 0.0 #11.925
    cov_coeff_t: 0 #0
    cov_per_feature: false
    projector: id
    random_projector: false
    sim_coeff: 1 #1
    std_coeff: 0.0 #35.026
    std_coeff_t: 0.0 #2.9199
    sim_coeff_t: 0.0 #0.10193
  prediction_propio:
    global_coeff: 0.0 #1.4108
  sigreg:
    coeff: 1.0
optimizer_type: Adam
output_dir: franka
output_root: ./pldm/checkpoints
eval_cfg:
  env_name: *env_name
  log_heatmap: false
  eval_l1: true
  task_type: franka
  probing:
    exe_probing: true
    l1_depth: *n_steps
    train_images_path: pldm_envs/franka/presaved_datasets/val_pairs_25_ep_1_timestep_300_sample_mix_direction_towards_bluebox_1p00_1p00_view_top_reverse/images.npy
    train_path: pldm_envs/franka/presaved_datasets/val_pairs_25_ep_1_timestep_300_sample_mix_direction_towards_bluebox_1p00_1p00_view_top_reverse/data.p
    val_images_path: pldm_envs/franka/presaved_datasets/val_pairs_25_ep_1_timestep_300_sample_mix_direction_towards_bluebox_1p00_1p00_view_top_reverse/images.npy #pldm_envs/franka/presaved_datasets/val_pairs_25_ep_1_timestep_300_sample_mix_direction_towards_bluebox_1_1/images.npy #pldm_envs/franka/presaved_datasets/val_pairs_25_ep_1_timestep_300_sample_towards_bluebox/images.npy
    val_path: pldm_envs/franka/presaved_datasets/val_pairs_25_ep_1_timestep_300_sample_mix_direction_towards_bluebox_1p00_1p00_view_top_reverse/data.p #pldm_envs/franka/presaved_datasets/val_pairs_25_ep_1_timestep_300_sample_mix_direction_towards_bluebox_1_1/data.p 
    probe_targets: 'locations,propio_vel,bluebox_locs' 
    locations:
      arch: 'conv'
      subclass: 'd'
    propio_vel:
      arch: 'conv'
      subclass: 'e'
    bluebox_locs:
      arch: 'conv'
      subclass: 'd'
    l2_probe_targets: 'locations'
    probe_mpc: false
    probe_wall: false
    probe_propio: true
    probe_encoder: true
    probe_preds: true
    use_opn_loss_func: *use_opn_loss_func
    vis_dynamics_closed_featuremap: false
    vis_dynamics_open_featuremap: false
    vis_encoder_featuremap: false
    
    vis_sample_length: 3 #ダイナミクス可視化時のタイムステップ
    epochs: 5 #5
    epochs_enc: 5 #5
    epochs_latent: 5 #5
    full_finetune: false
    lr: 0.0032 #0.0032 
    max_samples: 2000000
    max_samples_enc: 2000000
    schedule: Cosine
    visualize_probing: false #proberを用いたダイナミクスの可視化をするか否か
    visualize_dynamics: true #proberを用いないダイナミクスの可視化をするか否か 
    vis_long_horizon_eval: true #全てのval_dataset を使ったpca評価をするか否か
    load_prober: false
    train_prober: false #load_prober:falseの場合にproberをtrainさせるか否かを指定
  disable_planning: false
  franka_planning:
    n_envs: 4 #85
    n_envs_batch_size: 1 #16
    n_steps: 500 #192
    levels: "easy"
    easy:
      n_steps: 200
      pred_steps: 2 #その時刻の予測タイムステップ数 (学習時のタイムステップに合わせる)
      n_envs: 3 #80
      max_plan_length: 50 #タスク時に使われる
      plot_every: 10
      min_block_radius: 4
      max_block_radius: 9999
      override_config: true
    visualize_planning: true
    visualize_planning_videos: true
    log_pred_dist_every: 9999999
    plot_every: 16
    set_start_target_path: null #"../pldm_envs/diverse_maze/presaved_datasets/40maps_eval/trials.pt"
    action_repeat: 1
    action_repeat_mode: 'id'
    img_size: 64
    replan_every: 1
    image_obs: true
    stack_states: 1
    data_path: 'pldm_envs/franka/presaved_datasets/val_pairs_25_ep_1_timestep_300_sample_mix_direction_towards_bluebox_1p00_1p00_view_top_reverse/'
    max_dq: 0.05
    fps: 10 #FPS指定
    max_inner_steps: 500 #MPPI出力目標行動姿勢に近づけるまでに回す最大step数
    reach_eps: 1e-2 #MPPI出力目標姿勢と現在の姿勢の距離
    task:
      name: push_to_goal   # push_to_goal / reach_no_touch

      reach_no_touch:
        box_init_xyz: null                  # nullならresetで使うstart_posを採用
        box_hold_eps: 0.02                  # 成功判定: 箱が動いてない閾値(m)
        ee_success_eps: 0.03                # 成功判定: EE到達閾値(m)
        use_box: true           # falseなら goal画像生成時に箱を遠方へ

      push_to_goal:
        success_thresh: 0.05                # 既存の箱ゴール成功判定(m)


    level1:
      planner_type: PlannerType.MPPI
      min_step: 0
      max_step: 1
      max_plan_length: 50 #128 #一度に予測するホライズン
      sgd:
        action_change_reg: 0
        l2_reg: 0
        lr: 0.03
        n_iters: 200
      mppi:
        noise_sigma: 0.01 #5 #ノイズ共分散 0.01
        num_samples: 500 #500.  #ランダム行動列のサンプル数
        lambda_: 0.0025 #温度
        obs_coeff: 0.5 #1.0
        propio_coeff: 0.5 #0.0
        w_du: 1.0 #1.0 #MPPIの予測列の時間的変化をなめらかにする
        lpf_alpha: 1.0 #1.0 #ローパスフィルタ係数 #1.0: フィルタなし, 0.0: 前の行動を完全に引き継ぐ
      cem:
        num_samples: 500 #500 #1度にサンプリングする行動列の本数
        num_elites: 50 #50 #サンプルの中から成績上位として残す本数
        init_std: 0.1 #1.0 #初期の行動分布の標準偏差
        n_iters: 5 #5 #CEMの反復回数
        alpha: 0.1 #0.1 #分布更新の慣性
        clamp_actions: false 
        action_low: -1.0
        action_high: 1.0
        max_batch_size: 64
    val_from_train_ds: false #学習データセットで評価
    designate_start_goal_pos:  #タスク時にstart,goal_posを指定するか否か
      valid: true
      start_pos: [0.50, -0.05, 0.05] 
      goal_pos: [0.50, -0.15, 0.05]
  # d4rl_planning:
  #   n_envs: 10 #85
  #   n_envs_batch_size: 4 #16
  #   n_steps: 192
  #   levels: "medium"
  #   medium:
  #     n_steps: 200
  #     n_envs: 20 #80
  #     max_plan_length: 100 
  #     plot_every: 10
  #     min_block_radius: 4
  #     max_block_radius: 9999
  #     override_config: true
  #   log_pred_dist_every: 9999999
  #   plot_every: 16
  #   set_start_target_path: null #"../pldm_envs/diverse_maze/presaved_datasets/40maps_eval/trials.pt"
  #   action_repeat: 4
  #   action_repeat_mode: 'id'
  #   img_size: 64
  #   replan_every: 4
  #   image_obs: true
  #   stack_states: 1
  #   data_path: './pldm_envs/franka/presaved_datasets/val_pairs_50_ep_5_timestep_100/'
  #   level1:
  #     planner_type: PlannerType.MPPI
  #     min_step: 0
  #     max_step: 1
  #     max_plan_length: 64 #128
  #     sgd:
  #       action_change_reg: 0
  #       l2_reg: 0
  #       lr: 0.03
  #       n_iters: 200
  #     mppi:
  #       noise_sigma: 5 #5
  #       num_samples: 500 #500
  #       lambda_: 0.0025
  #   #d4rl specific
  #   position_only: true
quick_debug: false
run_group: pldm_franka
run_name: pldm_franka
run_project: Franka
save_every_n_epochs: 1
seed: 246
wandb: true
confirm_normalize: true